.sonarqube:
  stage: test
  variables:
    GIT_DEPTH: 0
    PROJECT_VERSION: "1.0"
    SONAR_SCANNER_OPTS: "-Xmx4g"
  image:
    name: $CI_REGISTRY/devops/sonar-scanner-cli:latest
    entrypoint: [""]
  tags:
    - 1c

.cacerts: &cacerts
  - keytool -cacerts -storepass changeit -noprompt -trustcacerts -importcert
      -alias ${SONAR_SSL_SERVER}
      -file "${SONAR_SSL_CERTIFICATE}"

.get_project_version: &get_project_version
  - export PROJECT_VERSION="1.0"

sonarqube on merge request:
  extends: .sonarqube
  script:
    - *cacerts
    - *get_project_version
    - >
      sonar-scanner
      -D"sonar.host.url=$SONAR_SERVER"
      -D"sonar.projectVersion=$PROJECT_VERSION"
      -D"sonar.login=$SONAR_LOGIN"
      -D"sonar.pullrequest.key=$CI_MERGE_REQUEST_IID"
      -D"sonar.pullrequest.branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
      -D"sonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
  rules:
    - if: $CI_MERGE_REQUEST_IID

sonarqube on tag:
  extends: .sonarqube
  script:
    - *cacerts
    - >
      sonar-scanner
      -D"sonar.host.url=$SONAR_SERVER"
      -D"sonar.projectVersion=$CI_COMMIT_TAG"
      -D"sonar.branch.name=$CI_DEFAULT_BRANCH"
      -D"sonar.login=$SONAR_LOGIN"
  rules:
    - if: $CI_COMMIT_TAG
